name: Build and Deploy Container

on:
    push:
        branches: [ "develop" ]

env:
    PROJECT_ID: "${{ secrets.PROJECT_ID}}"
    GAR_LOCATION: "us-central1"
    SERVICE: "create-pdf-by-date"
    REGION: "us-central1"
    TAG: "latest"

jobs:
    deploy:
        permissions:
            contents: "read"
            id-token: "write"

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Google Auth
              id: auth
              uses: "google-github-actions/auth@v2"
              with:
                credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

            - name: Docker Auth
              id: docker-auth
              uses: "docker/login-action@v3"
              with:
                username: _json_key
                password: "${{ secrets.GCP_CREDENTIALS }}"
                registry: "gcr.io"

            - name: Build and Push Container
              run: |-
                cp requirements.txt tsa/create_pdf_by_date/
                cd tsa/create_pdf_by_date/
                docker build -t "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ env.TAG }}" ./
                docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ env.TAG }}"
